spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fakedb
    username: fakeuser
    password: fakepassword
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true